#!/bin/bash

# fix distfeeds
sed -i "/ace8/d" /etc/opkg/distfeeds.conf
sed -i "/passwall_packages/d" /etc/opkg/distfeeds.conf
sed -i "/openwrt_helloworld/d" /etc/opkg/distfeeds.conf

uci -q batch <<-EOF
  set argon.@global[0]=global
  set argon.@global[0].primary='#0086d0'
  set argon.@global[0].dark_primary='#0086d0'
  set argon.@global[0].blur='10'
  set argon.@global[0].blur_dark='10'
  set argon.@global[0].transparency='0.5'
  set argon.@global[0].transparency_dark='0.5'
  set argon.@global[0].mode='light'
  set argon.@global[0].online_wallpaper='none'
  commit argon
EOF


exit 0
