#!/bin/bash

#!/bin/sh

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'
	add_list system.ntp.server='edu.ntp.org.cn'
	add_list system.ntp.server='ntp.tuna.tsinghua.edu.cn'
EOF
uci commit system

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/opkg/distfeeds.conf

sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R24.12.12'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='LEDE '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

# WAN & MODEM
uci -q batch <<-EOF
  set network.wan.username='pppoe_username'
  set network.wan.password='pppoe_password'
  set network.modem=interface
  set network.modem.proto='dhcp'
  set network.modem.device='wan'
  set network.modem.metric='90'
  commit network
EOF

# argon theme
uci -q batch <<-EOF
  set argon.@global[0]=global
  set argon.@global[0].primary='#ff6900'
  set argon.@global[0].dark_primary='#ff6900'
  set argon.@global[0].blur='10'
  set argon.@global[0].blur_dark='10'
  set argon.@global[0].transparency='0.5'
  set argon.@global[0].transparency_dark='0.5'
  set argon.@global[0].mode='light'
  set argon.@global[0].online_wallpaper='none'
  commit argon
EOF

# fix distfeeds
sed -i "/ace8/d" /etc/opkg/distfeeds.conf
sed -i "/passwall_packages/d" /etc/opkg/distfeeds.conf

#sysupgrade -f /etc/backup/redmi_ax6000-512mb-mwan3.tar.gz
rm -rf /etc/backup

sed -i '/exit 0/d' /etc/rc.local
cat >> /etc/rc.local <<-"EOF"
#/bin/ash

echo "255 255 255" > /sys/class/leds/rgb:network/multi_intensity
echo "255 255 255" > /sys/class/leds/rgb:status/multi_intensity

exit 0
EOF

/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart
/etc/init.d/passwall2 restart
/etc/init.d/ddns-go restart
/etc/init.d/udp2raw restart
/etc/init.d/zerotier restart
/etc/init.d/mosdns restart
/etc/init.d/dropbear restart

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
